name: conversation
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - -r requirements.txt
    #[non-prod]
    - pytest
    - pre-commit==2.17.0
    - flake8==7.0.0
    - autoflake
    - pypdf==3.9.1
    - pytest-asyncio==0.23.4
    - httpx==0.26.0